@TravelPlannerApi_HostAddress = http://localhost:4002/api

POST {{TravelPlannerApi_HostAddress}}/auth/register
Content-Type: application/json

{
    "username": "string",
    "password": "string"
}

###

POST {{TravelPlannerApi_HostAddress}}/auth/login
Content-Type: application/json

{
    "username": "string",
    "password": "string"
}

###

POST {{TravelPlannerApi_HostAddress}}/auth/refresh
Cookie: RefreshToken=d6b94519-93ae-4be5-bc7a-4e70f69335ea

###

GET {{TravelPlannerApi_HostAddress}}/values
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN0cmluZyIsIm5iZiI6MTcyNzU5OTEwMSwiZXhwIjoxNzI3NjAyNzAxLCJpYXQiOjE3Mjc1OTkxMDEsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMiIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDAwMSJ9.aWw1cPxL9gkFc9RVsdo2RZpeQN_KBKt_lw0P2ErlPc4

###
