export enum IntroStep {
    Welcome,
    AddTrip,
    SaveTrip,
    EditTrip,
    AddTripActivity,
    ExpandMap,
    AddPlaceMarker,
    SearchPlaceByAddress,
    SaveTripActivity,
    ExportKmz,
    CollapseMap,
    ActivityActionDetails,
    Final,
};