name: infrastructure
runtime:
  name: nodejs
  options:
    packagemanager: yarn
description: Pulumi scripts to deploy infrastructure
config:
  pulumi:tags:
    value:
      pulumi:template: azure-typescript
