name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.FRONTEND_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check for Frontend Changes
        id: changed_files
        run: |
          if [ $(git rev-list --count HEAD) -lt 2 ]; then
            echo "FRONTEND_CHANGED=false" >> $GITHUB_ENV
          else
            if git diff --name-only HEAD^ HEAD | grep -q '^frontend/'; then
              echo "FRONTEND_CHANGED=true" >> $GITHUB_ENV
            else
              echo "FRONTEND_CHANGED=false" >> $GITHUB_ENV
            fi
          fi

      - name: Get current git version
        id: get-version
        if: env.FRONTEND_CHANGED == 'true'
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "FRONTEND_VERSION=${VERSION}" >> $GITHUB_ENV
          echo "FRONTEND_VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        if: env.FRONTEND_CHANGED == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend Docker Image
        if: env.FRONTEND_CHANGED == 'true'
        run: |
          docker build -t mikhailgorodilov/travel-planner-webapp:${{ env.FRONTEND_VERSION }} ./frontend/travel-planner-webapp
          docker tag mikhailgorodilov/travel-planner-webapp:${{ env.FRONTEND_VERSION }} mikhailgorodilov/travel-planner-webapp:latest
          docker push mikhailgorodilov/travel-planner-webapp:${{ env.FRONTEND_VERSION }}
          docker push mikhailgorodilov/travel-planner-webapp:latest

  build-backend:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.BACKEND_VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check for Backend Changes
        id: changed_files
        run: |
          if [ $(git rev-list --count HEAD) -lt 2 ]; then
            echo "BACKEND_CHANGED=false" >> $GITHUB_ENV
          else
            if git diff --name-only HEAD^ HEAD | grep -q '^backend/'; then
              echo "BACKEND_CHANGED=true" >> $GITHUB_ENV
            else
              echo "BACKEND_CHANGED=false" >> $GITHUB_ENV
            fi
          fi

      - name: Get current git version
        id: get-version
        if: env.BACKEND_CHANGED == 'true'
        run: |
          VERSION=$(git rev-parse --short HEAD)
          echo "BACKEND_VERSION=${VERSION}" >> $GITHUB_ENV
          echo "BACKEND_VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        if: env.BACKEND_CHANGED == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker Image
        if: env.BACKEND_CHANGED == 'true'
        run: |
          docker build -t mikhailgorodilov/travel-planner-api:${{ env.BACKEND_VERSION }} ./backend/travel-planner-api
          docker tag mikhailgorodilov/travel-planner-api:${{ env.BACKEND_VERSION }} mikhailgorodilov/travel-planner-api:latest
          docker push mikhailgorodilov/travel-planner-api:${{ env.BACKEND_VERSION }}
          docker push mikhailgorodilov/travel-planner-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build-frontend, build-backend]
    env:
      API_VERSION: ${{ needs.build-backend.outputs.version }}
      WEBAPP_VERSION: ${{ needs.build-frontend.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Pulumi
        run: |
          curl -fsSL https://get.pulumi.com | sh
          export PATH=$PATH:$HOME/.pulumi/bin

      - name: Pulumi Login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: pulumi login

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Pulumi install dependencies
        working-directory: ./infrastructure
        run: yarn

      - name: Pulumi Up (Deploy Resources)
        working-directory: ./infrastructure
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          API_JWT_SECRET_KEY: ${{ secrets.API_JWT_SECRET_KEY }}
          API_ACCESS_TOKEN_EXPIRATION: ${{ vars.API_ACCESS_TOKEN_EXPIRATION }}
          API_REFRESH_TOKEN_EXPIRATION: ${{ vars.API_REFRESH_TOKEN_EXPIRATION }}
          API_VERSION: ${{ env.API_VERSION }}
          WEBAPP_VERSION: ${{ env.WEBAPP_VERSION }}
        run: pulumi up --yes --stack prod
